name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: '22.3.0'
  PNPM_VERSION: '9.5.0'
  HUSKY: 0

jobs:
  frontend-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}

      - run: cd app
      - run: pnpm install
      - run: pnpm format:check
